/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.event.master.pro.view.dashboard;

import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import org.event.master.pro.person.account.Account;
import org.event.master.pro.util.ImageUtil;
import static org.event.master.pro.util.ShowPanelUtil.*;
import org.event.master.pro.view.adminmanagement.AdminHomePanel;
import org.event.master.pro.view.Login;

/**
 *
 * @author Luisa
 */
public class AdminDashboard extends javax.swing.JFrame {

    public AdminDashboard() {
        initComponents();
        getContentPane().setLayout(new BorderLayout());
        openAdminPanel();

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        home = new javax.swing.JMenu();
        locationManagement = new javax.swing.JMenu();
        newLocationItem = new javax.swing.JMenuItem();
        showAllLocationItem = new javax.swing.JMenuItem();
        artistManagement = new javax.swing.JMenu();
        newArtistItem = new javax.swing.JMenuItem();
        consultAllArtist = new javax.swing.JMenuItem();
        speakerManagement = new javax.swing.JMenu();
        newSpeakerItem = new javax.swing.JMenuItem();
        showAllSpeakerItem = new javax.swing.JMenuItem();
        logoutButton = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        home.setText("Home");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        jMenuBar1.add(home);

        locationManagement.setText("Location");
        locationManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationManagementActionPerformed(evt);
            }
        });

        newLocationItem.setText("New Location");
        newLocationItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newLocationItemActionPerformed(evt);
            }
        });
        locationManagement.add(newLocationItem);

        showAllLocationItem.setText("Show All Locations");
        showAllLocationItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllLocationItemActionPerformed(evt);
            }
        });
        locationManagement.add(showAllLocationItem);

        jMenuBar1.add(locationManagement);

        artistManagement.setText("Artist");

        newArtistItem.setText("New Artist");
        newArtistItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newArtistItemActionPerformed(evt);
            }
        });
        artistManagement.add(newArtistItem);

        consultAllArtist.setText("Show All Artists");
        consultAllArtist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultAllArtistActionPerformed(evt);
            }
        });
        artistManagement.add(consultAllArtist);

        jMenuBar1.add(artistManagement);

        speakerManagement.setText("Speaker");

        newSpeakerItem.setText("New Speaker");
        newSpeakerItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSpeakerItemActionPerformed(evt);
            }
        });
        speakerManagement.add(newSpeakerItem);

        showAllSpeakerItem.setText("Show All Speakers");
        showAllSpeakerItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllSpeakerItemActionPerformed(evt);
            }
        });
        speakerManagement.add(showAllSpeakerItem);

        jMenuBar1.add(speakerManagement);

        logoutButton.setText("Log out");
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
        });
        jMenuBar1.add(logoutButton);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private JPanel mainPanel;
    private void locationManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationManagementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationManagementActionPerformed

    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        Account.logout();
        dispose();
        Login.showLogin();
    }//GEN-LAST:event_logoutButtonMouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        showAdminHome(this);
    }//GEN-LAST:event_homeMouseClicked

    private void newLocationItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newLocationItemActionPerformed
        showNewLocationPanel(this);
    }//GEN-LAST:event_newLocationItemActionPerformed

    private void showAllSpeakerItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllSpeakerItemActionPerformed
        showListSpeakerPanel(this);
    }//GEN-LAST:event_showAllSpeakerItemActionPerformed

    private void consultAllArtistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultAllArtistActionPerformed
        showListArtistPanel(this);
    }//GEN-LAST:event_consultAllArtistActionPerformed

    private void newArtistItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newArtistItemActionPerformed
        showNewArtistPanel(this);
    }//GEN-LAST:event_newArtistItemActionPerformed

    private void showAllLocationItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllLocationItemActionPerformed
        showListLocationPanel(this);
    }//GEN-LAST:event_showAllLocationItemActionPerformed

    private void newSpeakerItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSpeakerItemActionPerformed
        showNewSpeakerPanel(this);
    }//GEN-LAST:event_newSpeakerItemActionPerformed

    public static void openDashboard() {
    java.awt.EventQueue.invokeLater(() -> {
        AdminDashboard dash = new AdminDashboard();
        dash.setTitle("Admin Dashboard");
        dash.setSize(1000, 700);
        dash.setLocationRelativeTo(null);
        dash.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        dash.setVisible(true);
        dash.setResizable(false);
        ImageUtil.setIcon(dash);
    });
}
    
    public void openAdminPanel(){
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout());
        mainPanel.add(new AdminHomePanel(this), java.awt.BorderLayout.CENTER);
        getContentPane().add(mainPanel, BorderLayout.CENTER);
        mainPanel.revalidate();
        mainPanel.repaint();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu artistManagement;
    private javax.swing.JMenuItem consultAllArtist;
    private javax.swing.JMenu home;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu locationManagement;
    private javax.swing.JMenu logoutButton;
    private javax.swing.JMenuItem newArtistItem;
    private javax.swing.JMenuItem newLocationItem;
    private javax.swing.JMenuItem newSpeakerItem;
    private javax.swing.JMenuItem showAllLocationItem;
    private javax.swing.JMenuItem showAllSpeakerItem;
    private javax.swing.JMenu speakerManagement;
    // End of variables declaration//GEN-END:variables
}
