/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.event.master.pro.view.dashboard;

import org.event.master.pro.view.dashboard.*;
import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import org.event.master.pro.person.account.Account;
import org.event.master.pro.util.ImageUtil;
import static org.event.master.pro.util.ShowPanelUtil.*;
import org.event.master.pro.view.Login;
import org.event.master.pro.view.organizermanagement.OrganizerHomePanel;

/**
 *
 * @author Luisa
 */
public class OrganizerDashboard extends javax.swing.JFrame {

    public OrganizerDashboard() {
        initComponents();
        getContentPane().setLayout(new BorderLayout());
        openOrganizerPanel();

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        home = new javax.swing.JMenu();
        locationManagement = new javax.swing.JMenu();
        showAllLocationItem = new javax.swing.JMenuItem();
        artistManagement = new javax.swing.JMenu();
        consultAllArtist = new javax.swing.JMenuItem();
        speakerManagement = new javax.swing.JMenu();
        showAllSpeakerItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        showAllEvent = new javax.swing.JMenuItem();
        createEvent = new javax.swing.JMenuItem();
        logoutButton = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        home.setText("Home");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        jMenuBar1.add(home);

        locationManagement.setText("Location");
        locationManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationManagementActionPerformed(evt);
            }
        });

        showAllLocationItem.setText("Show All Locations");
        showAllLocationItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllLocationItemActionPerformed(evt);
            }
        });
        locationManagement.add(showAllLocationItem);

        jMenuBar1.add(locationManagement);

        artistManagement.setText("Artist");

        consultAllArtist.setText("Show All Artists");
        consultAllArtist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultAllArtistActionPerformed(evt);
            }
        });
        artistManagement.add(consultAllArtist);

        jMenuBar1.add(artistManagement);

        speakerManagement.setText("Speaker");

        showAllSpeakerItem.setText("Show All Speakers");
        showAllSpeakerItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllSpeakerItemActionPerformed(evt);
            }
        });
        speakerManagement.add(showAllSpeakerItem);

        jMenuBar1.add(speakerManagement);

        jMenu1.setText("Events");

        showAllEvent.setText("Show Events");
        showAllEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllEventActionPerformed(evt);
            }
        });
        jMenu1.add(showAllEvent);

        createEvent.setText("Create Event");
        createEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEventActionPerformed(evt);
            }
        });
        jMenu1.add(createEvent);

        jMenuBar1.add(jMenu1);

        logoutButton.setText("Log out");
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
        });
        jMenuBar1.add(logoutButton);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private JPanel mainPanel;
    private void locationManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationManagementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationManagementActionPerformed

    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        Account.logout();
        dispose();
        Login.showLogin();
    }//GEN-LAST:event_logoutButtonMouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        showOrganizerHome(this);
    }//GEN-LAST:event_homeMouseClicked

    private void showAllSpeakerItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllSpeakerItemActionPerformed
        showListSpeakerPanel(this);
    }//GEN-LAST:event_showAllSpeakerItemActionPerformed

    private void consultAllArtistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultAllArtistActionPerformed
        showListArtistPanel(this);
    }//GEN-LAST:event_consultAllArtistActionPerformed

    private void showAllLocationItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllLocationItemActionPerformed
        showListLocationPanel(this);
    }//GEN-LAST:event_showAllLocationItemActionPerformed

    private void showAllEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllEventActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showAllEventActionPerformed

    private void createEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEventActionPerformed
        showNewEventPanel(this);
    }//GEN-LAST:event_createEventActionPerformed

    public static void openDashboard() {
    java.awt.EventQueue.invokeLater(() -> {
        OrganizerDashboard dash = new OrganizerDashboard();
        dash.setTitle("Organizer Dashboard");
        dash.setSize(1000, 700);
        dash.setLocationRelativeTo(null);
        dash.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        ImageUtil.setIcon(dash);
        dash.setVisible(true);
        dash.setResizable(false);
    });
}
    
    public void openOrganizerPanel(){
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout());
        mainPanel.add(new OrganizerHomePanel(this), java.awt.BorderLayout.CENTER);
        getContentPane().add(mainPanel, BorderLayout.CENTER);
        mainPanel.revalidate();
        mainPanel.repaint();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu artistManagement;
    private javax.swing.JMenuItem consultAllArtist;
    private javax.swing.JMenuItem createEvent;
    private javax.swing.JMenu home;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu locationManagement;
    private javax.swing.JMenu logoutButton;
    private javax.swing.JMenuItem showAllEvent;
    private javax.swing.JMenuItem showAllLocationItem;
    private javax.swing.JMenuItem showAllSpeakerItem;
    private javax.swing.JMenu speakerManagement;
    // End of variables declaration//GEN-END:variables
}
