/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.event.master.pro.view.adminmanagement.speaker;

import java.awt.Color;
import java.util.List;
import javax.swing.JFrame;
import org.event.master.pro.person.speaker.Speaker;
import org.event.master.pro.person.speaker.SpeakerDAO;
import org.event.master.pro.util.FormatUtil;
import static org.event.master.pro.util.ShowPanelUtil.showListSpeakerPanel;
import org.event.master.pro.util.UIUtil;

/**
 *
 * @author Luisa
 */
public class SpeakerConsultPanel extends javax.swing.JPanel {

    Speaker speaker = new Speaker();
    SpeakerDAO sdao = new SpeakerDAO();
    private final JFrame container;
    private String doc;

    /**
     * Creates new form SeeSpeakerPanel
     */
    public SpeakerConsultPanel(JFrame container, String document) {
        initComponents();
        propertiePlaceHolder();
        this.container = container;
        this.doc = document;
        artistData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        speakerDocumentNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        artistName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        artistMusicalGenre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        artistRequirements = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        speakerPrice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        artistEmail = new javax.swing.JTextField();
        artistPhoneNumber = new javax.swing.JTextField();
        artistListButton = new javax.swing.JButton();

        jLabel2.setText("Document Number");

        jLabel3.setText("Name");

        jLabel4.setText("Speciality");

        jLabel5.setText("Requirements");

        artistRequirements.setColumns(20);
        artistRequirements.setRows(5);
        jScrollPane1.setViewportView(artistRequirements);

        jLabel6.setText("Price");

        jLabel7.setText("Email");

        jLabel8.setText("Phone Number");

        artistListButton.setText("Ok");
        artistListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artistListButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(artistListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(174, 174, 174)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(artistMusicalGenre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(artistName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(speakerDocumentNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(artistEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(speakerPrice, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(artistPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(speakerDocumentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(speakerPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(artistName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(artistEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(artistMusicalGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(artistPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(artistListButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void artistListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artistListButtonActionPerformed
        System.out.println("yendo a " + container.getName());
        showListSpeakerPanel(container);
    }//GEN-LAST:event_artistListButtonActionPerformed

    public void propertiePlaceHolder() {
        UIUtil.propertiesText(speakerDocumentNumber, Color.WHITE);
        UIUtil.propertiesText(artistName, Color.WHITE);
        UIUtil.propertiesText(artistEmail, Color.WHITE);
        UIUtil.propertiesText(artistMusicalGenre, Color.WHITE);
        UIUtil.propertiesText(artistPhoneNumber, Color.WHITE);
        UIUtil.propertiesText(speakerPrice, Color.WHITE);
        UIUtil.propertiesText(artistRequirements, Color.WHITE);
    }

    public void artistData() {
        List<Speaker> speakerToSee = sdao.viewSpeakerDetail(doc);
        for (Speaker a : speakerToSee) {
            speakerDocumentNumber.setText(a.getDocumenNumber());
            artistName.setText(a.getName());
            artistEmail.setText(a.getMail());
            artistMusicalGenre.setText(a.getSpeciality());
            artistPhoneNumber.setText(a.getPhone());
            speakerPrice.setText(FormatUtil.formatNumber(a.getPrice()));
            artistRequirements.setText(a.getRequirements());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField artistEmail;
    private javax.swing.JButton artistListButton;
    private javax.swing.JTextField artistMusicalGenre;
    private javax.swing.JTextField artistName;
    private javax.swing.JTextField artistPhoneNumber;
    private javax.swing.JTextArea artistRequirements;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField speakerDocumentNumber;
    private javax.swing.JTextField speakerPrice;
    // End of variables declaration//GEN-END:variables
}
