/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.event.master.pro.view.adminmanagement.speaker;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.event.master.pro.person.speaker.SpeakerDAO;
import static org.event.master.pro.util.ShowPanelUtil.*;
import org.event.master.pro.util.UIUtil;

/**
 *
 * @author Luisa
 */
public class SpeakerCreatePanel extends javax.swing.JPanel {
    SpeakerDAO speaker = new SpeakerDAO();
    private final JFrame container;
    /**
     * Creates new form NewSpeakerPanel
     */
    public SpeakerCreatePanel(JFrame container) {
        initComponents();
        this.container = container;
        setPlaceHolder();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        speakerEmail = new javax.swing.JTextField();
        speakerPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        speakerRequirements = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        documentTypeSpeaker = new javax.swing.JComboBox<>();
        speakerSpeciality = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        saveSpeaker = new javax.swing.JButton();
        speakerName = new javax.swing.JTextField();
        speakerPhoneNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        speakerDocumentNumber = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel6.setText("Price");

        speakerRequirements.setColumns(20);
        speakerRequirements.setRows(5);
        jScrollPane1.setViewportView(speakerRequirements);

        jLabel9.setText("Document Number");

        jLabel5.setText("Requeriments");

        documentTypeSpeaker.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CC", "CE", "NIT", "PAS", "PPT", "RC", "TI" }));
        documentTypeSpeaker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentTypeSpeakerActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Speciality");

        saveSpeaker.setText("Save");
        saveSpeaker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveSpeakerActionPerformed(evt);
            }
        });

        jLabel3.setText("Name");

        jLabel8.setText("Phone Number");

        jLabel2.setText("Document Type");

        jLabel7.setText("Email");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveSpeaker, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(speakerPhoneNumber)
                            .addComponent(speakerEmail)
                            .addComponent(speakerPrice)
                            .addComponent(speakerSpeciality)
                            .addComponent(speakerName)
                            .addComponent(speakerDocumentNumber)
                            .addComponent(documentTypeSpeaker, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)))
                        .addContainerGap(50, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(documentTypeSpeaker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(speakerDocumentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(speakerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(speakerPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(speakerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(speakerPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(speakerSpeciality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveSpeaker)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        showAdminHome(container);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void saveSpeakerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveSpeakerActionPerformed
        if (speakerDocumentNumber.getText() == null || speakerDocumentNumber.getText().isEmpty() ||
            documentTypeSpeaker.getSelectedItem() == null ||
            speakerName.getText() == null || speakerName.getText().isEmpty() ||
            speakerEmail.getText() == null || speakerEmail.getText().isEmpty() ||
            speakerPrice.getText() == null || speakerPrice.getText().isEmpty() ||    
            speakerRequirements.getText() == null || speakerRequirements.getText().isEmpty() ||
            speakerSpeciality.getText() == null || speakerSpeciality.getText().isEmpty() ||
            speakerPhoneNumber.getText() == null || speakerPhoneNumber.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "All required fields must be filled in.");
            return;
        }
        
        if (!speakerPrice.getText().matches("\\d+(\\.\\d+)?")) {
            JOptionPane.showMessageDialog(this, "The price must be a valid numeric value.");
            return;
        }
        if (!speakerDocumentNumber.getText().matches("\\d+(\\.\\d+)?")) {
            JOptionPane.showMessageDialog(this, "The document number must be a valid numeric value.");
            return;
        }

        if (!speakerPhoneNumber.getText().matches("\\d+(\\.\\d+)?")) {
            JOptionPane.showMessageDialog(this, "The phone number must be a valid numeric value.");
            return;
        }
        String documentType, documentNumber, name, mail, speciality, phoneNumber, requirements;
        double price;
        documentType = String.valueOf(documentTypeSpeaker.getSelectedItem());
        documentNumber = speakerDocumentNumber.getText();
        name = speakerName.getText();
        mail = speakerEmail.getText();
        speciality = speakerSpeciality.getText();
        phoneNumber = speakerPhoneNumber.getText();
        price = Double.parseDouble(speakerPrice.getText());
        requirements = speakerRequirements.getText();
        boolean message = speaker.registerSpeaker(documentType, documentNumber, name, mail, speciality, phoneNumber, requirements,price);
        if (!message) {
            showListSpeakerPanel(container);
        }else{
            JOptionPane.showMessageDialog(null, "There is already an speaker with this same document number");
        }
    }//GEN-LAST:event_saveSpeakerActionPerformed

    private void documentTypeSpeakerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentTypeSpeakerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_documentTypeSpeakerActionPerformed

    public void setPlaceHolder(){
        UIUtil.setPlaceHolder("Document number", speakerDocumentNumber);
        UIUtil.setPlaceHolder("Name", speakerName);
        UIUtil.setPlaceHolder("Speciality", speakerSpeciality);
        UIUtil.setPlaceHolder("Price", speakerPrice);
        UIUtil.setPlaceHolder("Phone number", speakerPhoneNumber);
        UIUtil.setPlaceHolder("Requeriments", speakerRequirements);
        UIUtil.setPlaceHolder("Mail", speakerEmail);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> documentTypeSpeaker;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saveSpeaker;
    private javax.swing.JTextField speakerDocumentNumber;
    private javax.swing.JTextField speakerEmail;
    private javax.swing.JTextField speakerName;
    private javax.swing.JTextField speakerPhoneNumber;
    private javax.swing.JTextField speakerPrice;
    private javax.swing.JTextArea speakerRequirements;
    private javax.swing.JTextField speakerSpeciality;
    // End of variables declaration//GEN-END:variables
}
