/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.event.master.pro.view.adminmanagement.location;

import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import org.event.master.pro.event.location.Location;
import org.event.master.pro.event.location.LocationDAO;
import org.event.master.pro.person.account.Account;
import static org.event.master.pro.util.ShowPanelUtil.*;

/**
 *
 * @author Luisa
 */
public class LocationListPanel extends javax.swing.JPanel {

    private final JFrame container;
    LocationDAO ldao = new LocationDAO();
    Account account = new Account();
    private static String id;

    /**
     * Creates new form LocationListPanel
     */
    public LocationListPanel(JFrame container) {
        initComponents();
        this.container = container;
        tableLocation();
        jScrollPane1.getViewport().setBackground(UIManager.getColor("Table.background"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        locationTable = new javax.swing.JTable();

        locationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Address", "Capacity", "City", "Availability", "See", "Edit", "Delete", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(locationTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableLocation() {
        List<Location> loc = ldao.consultLocation();
        DefaultTableModel modelTableArtist = (DefaultTableModel) locationTable.getModel();
        for (Location l : loc) {
            modelTableArtist.addRow(new Object[]{l.getName(), l.getAddress(), l.getCity(), l.getCapacity(), l.isAvailability(), "See", "Edit", "Delete", l.getIdLocation()});
        }
        buttonsEvent();
        locationTable.getColumnModel().getColumn(8).setMinWidth(0);
        locationTable.getColumnModel().getColumn(8).setMaxWidth(0);
        locationTable.getColumnModel().getColumn(8).setPreferredWidth(0);
        //UIUtil.hideButtons(account.getRol(), locationTable);
    }

    //Eventos para los botones Edit y Delete ya que fueron elementos añadidos manualmente a la tabla
    private void buttonsEvent() {
        locationTable.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = locationTable.rowAtPoint(evt.getPoint());
                int column = locationTable.columnAtPoint(evt.getPoint());
                id = locationTable.getValueAt(row, 8).toString();
                if (column == locationTable.getColumnModel().getColumnIndex("Edit")) {
                    showEditLocationPanel(container, id);
                } else if (column == locationTable.getColumnModel().getColumnIndex("Delete")) {
                    int confirmado = JOptionPane.showConfirmDialog(
                            null,
                            "Are you sure you want to delete the location?",
                            "Confirm",
                            JOptionPane.YES_NO_OPTION
                    );
                    if (confirmado == JOptionPane.YES_OPTION) {
                        try {
                            ldao.changeStatusLocation(id);
                            showListLocationPanel(container);
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(
                                null,
                                e.getMessage(),
                                "Cannot eelete this location",
                                JOptionPane.WARNING_MESSAGE
            );
                        }
                    }
                } else if (column == locationTable.getColumnModel().getColumnIndex("See")) {
                    showSeeLocationPanel(container, id);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable locationTable;
    // End of variables declaration//GEN-END:variables
}
