/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.event.master.pro.view.adminmanagement.location;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.event.master.pro.event.location.Location;
import org.event.master.pro.event.location.LocationDAO;
import org.event.master.pro.util.FileUtil;
import static org.event.master.pro.util.ShowPanelUtil.*;
import org.event.master.pro.util.UIUtil;

/**
 *
 * @author Luisa
 */
public class LocationEditPanel extends javax.swing.JPanel {
    Location location = new Location();
    LocationDAO ldao = new LocationDAO();
    private String id;
    private final JFrame container;
    /**
     * Creates new form LocationEditPanel
     */
    public LocationEditPanel(JFrame container, String id) {
        initComponents();
        this.container = container;
        this.id = id;
        locationData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        locationName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        locationType = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        locationPrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        locationCapacity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        editLocation = new javax.swing.JButton();
        additionalConsideration = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        locationAddress = new javax.swing.JTextField();
        locationCity = new javax.swing.JComboBox<>();
        locationDepartment = new javax.swing.JComboBox<>();

        jLabel2.setText("Location type");

        locationType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arena", "Auditorio", "Bar", "Centro de convenciones", "Estadio", "Hotel", "Parque", "Teatro" }));

        jLabel9.setText("Name");

        jLabel6.setText("Price");

        jLabel5.setText("Additional Considerations");

        locationPrice.setPreferredSize(null);

        jLabel4.setText("Capacity");

        locationCapacity.setPreferredSize(null);

        jLabel3.setText("Address");

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        editLocation.setText("Save");
        editLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editLocationActionPerformed(evt);
            }
        });

        additionalConsideration.setPreferredSize(null);

        jLabel8.setText("City");

        jLabel7.setText("Department");

        locationAddress.setPreferredSize(null);

        locationCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationCityActionPerformed(evt);
            }
        });

        locationDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Amazonas", "Antioquia", "Arauca", "Atlántico", "Bolívar", "Boyacá", "Caldas", "Caquetá", "Casanare", "Cauca", "Cesar", "Chocó", "Córdoba", "Cundinamarca", "Guainía", "Guaviare", "Huila", "La Guajira", "Magdalena", "Meta", "Nariño", "Norte de Santander", "Putumayo", "Quindío", "Risaralda", "San Andrés, Providencia y Santa Catalina", "Santander", "Sucre", "Tolima", "Valle del Cauca", "Vaupés", "Vichada" }));
        locationDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationDepartmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(locationPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(locationCity, javax.swing.GroupLayout.Alignment.LEADING, 0, 300, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(locationName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(locationAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(locationType, 0, 300, Short.MAX_VALUE)
                    .addComponent(locationCapacity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(locationDepartment, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(additionalConsideration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(151, 151, 151))
            .addGroup(layout.createSequentialGroup()
                .addGap(422, 422, 422)
                .addComponent(editLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(locationType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(locationCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(locationPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(locationDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(additionalConsideration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editLocation)
                    .addComponent(cancelButton))
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        showListLocationPanel(container);
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    public void propertiePlaceHolder(){
        UIUtil.setPlaceHolder("Name", locationName);
        UIUtil.setPlaceHolder("Address", locationAddress);
        UIUtil.setPlaceHolder("Capacity", locationCapacity);
        UIUtil.setPlaceHolder("Price", locationPrice);
    }
    
    public void locationData(){
        Location l = ldao.viewLocationDetail(id);
            locationName.setText(l.getName());
            locationType.setSelectedItem(l.getType());
            locationAddress.setText(l.getAddress());
            locationCapacity.setText(String.valueOf(l.getCapacity()));
            locationPrice.setText(String.valueOf(l.getPrice()));
            locationDepartment.setSelectedItem(l.getDepartment());
            locationCity.setSelectedItem(l.getCity());
            additionalConsideration.setText(l.getConsideration());
        
    }
    
    private void editLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editLocationActionPerformed
        List<Location> location = new ArrayList<Location>();
        String name, address, city, department, type, consideration = "No aplica";
        int capacity;
        double price;
        name = locationName.getText();
        address = locationAddress.getText();
        city = locationCity.getSelectedItem().toString();
        department = locationDepartment.getSelectedItem().toString();
        capacity = Integer.parseInt(locationCapacity.getText());
        type = locationType.getSelectedItem().toString();
        if(!additionalConsideration.getText().isBlank()){
            consideration = additionalConsideration.getText();
        }
        price = Double.parseDouble(locationPrice.getText());
        Location l = new Location(name, address, capacity, city, department, type, price, consideration);
        location.add(l);
        ldao.editLocation(location, id);
        showListLocationPanel(container);
        
    }//GEN-LAST:event_editLocationActionPerformed

    private void locationCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationCityActionPerformed

    }//GEN-LAST:event_locationCityActionPerformed

    private void locationDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationDepartmentActionPerformed
        selectCity();
    }//GEN-LAST:event_locationDepartmentActionPerformed

    public void selectCity(){
        FileUtil.uploadCity(locationDepartment);
        String departmentSelected = locationDepartment.getSelectedItem().toString();
        locationCity.removeAllItems();
        if (departmentSelected != null && FileUtil.departamentMap.containsKey(departmentSelected)) {
            for (String city : FileUtil.departamentMap.get(departmentSelected)) {
                locationCity.addItem(city);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField additionalConsideration;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton editLocation;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField locationAddress;
    private javax.swing.JTextField locationCapacity;
    private javax.swing.JComboBox<String> locationCity;
    private javax.swing.JComboBox<String> locationDepartment;
    private javax.swing.JTextField locationName;
    private javax.swing.JTextField locationPrice;
    private javax.swing.JComboBox<String> locationType;
    // End of variables declaration//GEN-END:variables
}
