/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.event.master.pro.view.organizermanagement.event;

import java.sql.SQLException;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import org.event.master.pro.event.Event.Event;
import org.event.master.pro.event.Event.EventDAO;
import static org.event.master.pro.util.ShowPanelUtil.showEditEventPanel;
import static org.event.master.pro.util.ShowPanelUtil.showSeeEventPanel;

/**
 *
 * @author Luisa
 */
public class ListEventPanel extends javax.swing.JPanel {

    EventDAO edao = new EventDAO();
    private final JFrame container;
    private List<Event> events;

    /**
     * Creates new form EventListPanel
     */
    public ListEventPanel(JFrame container) {
        initComponents();
        this.container = container;
        jScrollPane1.getViewport().setBackground(UIManager.getColor("Table.background"));
        String status = "Created";
        tableEvent(status);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        eventTable = new javax.swing.JTable();
        statusCombobox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        eventTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Date", "Status", "Quorum", "See", "Edit", "Cancel", "Type", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(eventTable);

        statusCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Created", "Published", "In Progress", "Rescheduled", "Finished", "Cancelled" }));

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Filter by status:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 982, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(520, 520, 520)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(statusCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel modelTableEvent = (DefaultTableModel) eventTable.getModel();
        modelTableEvent.setRowCount(0);
        tableEvent(statusCombobox.getSelectedItem().toString());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tableEvent(String status) {
        events = edao.consultEvent(status);
        DefaultTableModel modelTableEvent = (DefaultTableModel) eventTable.getModel();
        for (Event e : events) {
            modelTableEvent.addRow(new Object[]{e.getName(), e.getDateTimeEvent(), e.getStatusEvent(), e.getParticipantsNumbers(), "See", "Edit", "Cancel", e.getType(), e.getIdEvent()});
        }
        //UIUtil.hideButtons(account.getRol(), speakerTable);
        buttonsEvent();
    }

    private void buttonsEvent() {
        eventTable.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonFunctional(evt);
            }
        });
    }

    public void buttonFunctional(java.awt.event.MouseEvent evt) {
        int row = eventTable.rowAtPoint(evt.getPoint());
        int column = eventTable.columnAtPoint(evt.getPoint());
        String type = eventTable.getValueAt(row, 7).toString();
        int idEvent = Integer.parseInt(eventTable.getValueAt(row, 8).toString());
        if (column == eventTable.getColumnModel().getColumnIndex("Edit")) {
            try {
                showEditEventPanel(container, idEvent, type);
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "SQL Error: " + e.getMessage());
            }
        } else if (column == eventTable.getColumnModel().getColumnIndex("Cancel")) {
            int confirmado = JOptionPane.showConfirmDialog(
                    null,
                    "Are you sure you want to cancel the event?",
                    "Confirm",
                    JOptionPane.YES_NO_OPTION
            );
            if (confirmado == JOptionPane.YES_OPTION) {
                //artist.changeStatusArtist(document);
                //switchToPanel(container, new ArtistListPanel(container));
            }
        } else if (column == eventTable.getColumnModel().getColumnIndex("See")) {
            try {
                showSeeEventPanel(container, idEvent, type);
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "SQL Error: " + e.getMessage());
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable eventTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> statusCombobox;
    // End of variables declaration//GEN-END:variables
}
