/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.event.master.pro.view.adminmanagement.artist;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.event.master.pro.person.artist.ArtistDAO;
import static org.event.master.pro.util.ShowPanelUtil.*;
import org.event.master.pro.util.UIUtil;

/**
 *
 * @author Luisa
 */
public class ArtistCreatePanel extends javax.swing.JPanel {
    ArtistDAO adao = new ArtistDAO();
    private final JFrame container;
    /**
     * Creates new form NewArtistPanel
     */
    public ArtistCreatePanel(JFrame container) {
        initComponents();
        this.container = container;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        documentTypeArtist = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        artistDocumentNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        artistName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        artistMusicalGenre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        artistRequirements = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        artistPrice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        artistEmail = new javax.swing.JTextField();
        artistPhoneNumber = new javax.swing.JTextField();
        saveArtist = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        jLabel9.setText("Document type");

        documentTypeArtist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CC", "CE", "NIT", "PAS", "PPT", "RC", "TI" }));

        jLabel2.setText("Document Number");

        jLabel3.setText("Name");

        jLabel4.setText("Musical Genre");

        jLabel5.setText("Requeriments");

        artistRequirements.setColumns(20);
        artistRequirements.setRows(5);
        artistRequirements.setToolTipText("");
        artistRequirements.setWrapStyleWord(true);
        jScrollPane1.setViewportView(artistRequirements);

        jLabel6.setText("Price");

        jLabel7.setText("Email");

        jLabel8.setText("Phone Number");

        saveArtist.setText("Save");
        saveArtist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveArtistActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                        .addComponent(saveArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addComponent(artistPhoneNumber, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(artistEmail, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(artistPrice, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(artistMusicalGenre, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(artistName, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(artistDocumentNumber, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(documentTypeArtist, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {artistDocumentNumber, artistEmail, artistMusicalGenre, artistName, artistPhoneNumber, artistPrice, documentTypeArtist, jScrollPane1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(documentTypeArtist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(artistDocumentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(artistName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(artistMusicalGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(artistPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(artistEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(artistPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveArtist)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setPlaceHolder(){
        UIUtil.setPlaceHolder("Document number", artistDocumentNumber);
        UIUtil.setPlaceHolder("Name", artistName);
        UIUtil.setPlaceHolder("Musical genre", artistMusicalGenre);
        UIUtil.setPlaceHolder("Price", artistPrice);
        UIUtil.setPlaceHolder("Phone number", artistPhoneNumber);
        UIUtil.setPlaceHolder("Requeriments", artistRequirements);
        UIUtil.setPlaceHolder("Mail", artistEmail);
    }
    
    private void saveArtistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveArtistActionPerformed
        
        if (artistDocumentNumber.getText() == null || artistDocumentNumber.getText().isEmpty() ||
            documentTypeArtist.getSelectedItem() == null ||
            artistName.getText() == null || artistName.getText().isEmpty() ||
            artistEmail.getText() == null || artistEmail.getText().isEmpty() ||
            artistPrice.getText() == null || artistPrice.getText().isEmpty() ||    
            artistRequirements.getText() == null || artistRequirements.getText().isEmpty() ||
            artistMusicalGenre.getText() == null || artistMusicalGenre.getText().isEmpty() ||
            artistPhoneNumber.getText() == null || artistPhoneNumber.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "All required fields must be filled in.");
            return;
        }
        
        if (!artistPrice.getText().matches("\\d+(\\.\\d+)?")) {
            JOptionPane.showMessageDialog(this, "The price must be a valid numeric value.");
            return;
        }
        if (!artistDocumentNumber.getText().matches("\\d+(\\.\\d+)?")) {
            JOptionPane.showMessageDialog(this, "The document number must be a valid numeric value.");
            return;
        }

        if (!artistPhoneNumber.getText().matches("\\d+(\\.\\d+)?")) {
            JOptionPane.showMessageDialog(this, "The phone number must be a valid numeric value.");
            return;
        }
        String aDocumentType, aDocumentNumber, aName, aMail, aMusicalGenre, aPhoneNumber, aRequirements;
        double aPrice;
        aDocumentType = String.valueOf(documentTypeArtist.getSelectedItem());
        aDocumentNumber = artistDocumentNumber.getText();
        aName = artistName.getText();
        aMail = artistEmail.getText();
        aMusicalGenre = artistMusicalGenre.getText();
        aPhoneNumber = artistPhoneNumber.getText();
        aPrice = Double.parseDouble(artistPrice.getText());
        aRequirements = artistRequirements.getText();
        boolean message = adao.registerArtist(aDocumentType, aDocumentNumber, aName, aMail, aMusicalGenre, aPhoneNumber, aRequirements, aPrice);
        if (!message) {
            showAdminHome(container);

        }else{
            JOptionPane.showMessageDialog(null, "There is already an artist with this same document number");
        }
    }//GEN-LAST:event_saveArtistActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        showAdminHome(container);
    }//GEN-LAST:event_cancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField artistDocumentNumber;
    private javax.swing.JTextField artistEmail;
    private javax.swing.JTextField artistMusicalGenre;
    private javax.swing.JTextField artistName;
    private javax.swing.JTextField artistPhoneNumber;
    private javax.swing.JTextField artistPrice;
    private javax.swing.JTextArea artistRequirements;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> documentTypeArtist;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saveArtist;
    // End of variables declaration//GEN-END:variables
}
