/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.event.master.pro.view.adminmanagement;

import javax.swing.JFrame;
import org.event.master.pro.event.location.LocationDAO;
import org.event.master.pro.person.speaker.SpeakerDAO;
import org.event.master.pro.person.artist.ArtistDAO;
import static org.event.master.pro.util.ShowPanelUtil.*;
import org.event.master.pro.util.UIUtil;

/**
 *
 * @author Luisa
 */
public class AdminHomePanel extends javax.swing.JPanel {

    private final JFrame container;

    /**
     * Creates new form AdminHomePanel
     */
    public AdminHomePanel(JFrame container) {
        this.container = container;
        initComponents();
        showTotal();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        seeMoreArtistButton = new javax.swing.JButton();
        seeMoreSpeakerButton = new javax.swing.JButton();
        seeMoreLocationButton = new javax.swing.JButton();
        newArtistButton = new javax.swing.JButton();
        newSpeakerButton = new javax.swing.JButton();
        newLocationButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        nLocation = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        nArtist = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        nSpeaker = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1000, 545));

        jLabel5.setText("Recently Added Artists");

        jLabel6.setText("Recently Added Speakers");

        jLabel7.setText("Available Locations");

        seeMoreArtistButton.setText("See more...");
        seeMoreArtistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeMoreArtistButtonActionPerformed(evt);
            }
        });

        seeMoreSpeakerButton.setText("See more...");
        seeMoreSpeakerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeMoreSpeakerButtonActionPerformed(evt);
            }
        });

        seeMoreLocationButton.setText("See more...");
        seeMoreLocationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeMoreLocationButtonActionPerformed(evt);
            }
        });

        newArtistButton.setText("New Artist");
        newArtistButton.setName(""); // NOI18N
        newArtistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newArtistButtonActionPerformed(evt);
            }
        });

        newSpeakerButton.setText("New Speaker");
        newSpeakerButton.setName(""); // NOI18N
        newSpeakerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSpeakerButtonActionPerformed(evt);
            }
        });

        newLocationButton.setText("New Location");
        newLocationButton.setName(""); // NOI18N
        newLocationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newLocationButtonActionPerformed(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(308, 47));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        nLocation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(nLocation, java.awt.BorderLayout.CENTER);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Total Locations");
        jPanel1.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jPanel2.setPreferredSize(new java.awt.Dimension(308, 47));
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Total Artists");
        jLabel4.setPreferredSize(new java.awt.Dimension(80, 16));
        jPanel2.add(jLabel4, java.awt.BorderLayout.PAGE_START);

        nArtist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(nArtist, java.awt.BorderLayout.CENTER);

        jPanel3.setPreferredSize(new java.awt.Dimension(308, 47));
        jPanel3.setRequestFocusEnabled(false);
        jPanel3.setLayout(new java.awt.BorderLayout());

        nSpeaker.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nSpeaker.setToolTipText("");
        jPanel3.add(nSpeaker, java.awt.BorderLayout.CENTER);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Total Speakers");
        jLabel3.setPreferredSize(new java.awt.Dimension(80, 16));
        jPanel3.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(433, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(newSpeakerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seeMoreSpeakerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(newLocationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seeMoreLocationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(newArtistButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seeMoreArtistButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(433, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator3)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jSeparator2)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newArtistButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seeMoreArtistButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newSpeakerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seeMoreSpeakerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newLocationButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seeMoreLocationButton))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(488, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void seeMoreArtistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeMoreArtistButtonActionPerformed
        
        showListArtistPanel(container);
    }//GEN-LAST:event_seeMoreArtistButtonActionPerformed

    private void seeMoreSpeakerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeMoreSpeakerButtonActionPerformed
        showListSpeakerPanel(container);
    }//GEN-LAST:event_seeMoreSpeakerButtonActionPerformed

    private void seeMoreLocationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeMoreLocationButtonActionPerformed
        showListLocationPanel(container);
    }//GEN-LAST:event_seeMoreLocationButtonActionPerformed

    private void newArtistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newArtistButtonActionPerformed
        showNewArtistPanel(container);
    }//GEN-LAST:event_newArtistButtonActionPerformed

    private void newSpeakerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSpeakerButtonActionPerformed
        showNewSpeakerPanel(container);
    }//GEN-LAST:event_newSpeakerButtonActionPerformed

    private void newLocationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newLocationButtonActionPerformed
        showNewLocationPanel(container);
    }//GEN-LAST:event_newLocationButtonActionPerformed

    public static void showAdminHome(JFrame container) {
        switchToPanel(container, new AdminHomePanel(container));
    }
    
    public static void showPanel(JFrame container){
        
    }
    
    public static void lastArtist(){
        
    }
    
    public void showTotal(){
        LocationDAO location = new LocationDAO();
        ArtistDAO artist = new ArtistDAO();
        SpeakerDAO speaker = new SpeakerDAO();
        nLocation.setText(String.valueOf(location.countAllLocationActive()));
        nArtist.setText(String.valueOf(artist.countAllArtist()));
        nSpeaker.setText(String.valueOf(speaker.countAllSpeaker()));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel nArtist;
    private javax.swing.JLabel nLocation;
    private javax.swing.JLabel nSpeaker;
    private javax.swing.JButton newArtistButton;
    private javax.swing.JButton newLocationButton;
    private javax.swing.JButton newSpeakerButton;
    private javax.swing.JButton seeMoreArtistButton;
    private javax.swing.JButton seeMoreLocationButton;
    private javax.swing.JButton seeMoreSpeakerButton;
    // End of variables declaration//GEN-END:variables
}
